version: '3'
services:
  wordpress:
    build:
      context: '${BACK_END}'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BACK_END=${BACK_END}'
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'WP_VERSION=${WP_VERSION}'
        - 'XDEBUG=${XDEBUG}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
        - 'DB_HOST=${DB_HOST}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${SERVER_ROOT}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${WORDPRESS_HOST_HTTP_PORT}:80'
  mysql:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'UPLOAD_LIMIT=300M'
    ports:
      - '${PMA_PORT}:80'
volumes: {}
