FROM ghcr.io/deck-app/apache:v8.0
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php8-openssl php8-sysvmsg php8-curl
RUN apk add --no-cache tar

RUN mkdir -p /app
RUN mkdir -p /var/preview
ARG WP_VERSION
COPY httpd.conf /etc/apache2/httpd.conf
COPY httpd.conf /app/httpd.conf
RUN curl -o /app/wordpress.tar.gz -fL "https://wordpress.org/wordpress-$WP_VERSION.tar.gz"; \
	tar -xzf /app/wordpress.tar.gz -C /app/; \
	rm /app/wordpress.tar.gz; \
	[ ! -e /app/wordpress/.htaccess ]; \
	{ \
		echo '# BEGIN WordPress'; \
		echo ''; \
		echo 'RewriteEngine On'; \
		echo 'RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]'; \
		echo 'RewriteBase /'; \
		echo 'RewriteRule ^index\.php$ - [L]'; \
		echo 'RewriteCond %{REQUEST_FILENAME} !-f'; \
		echo 'RewriteCond %{REQUEST_FILENAME} !-d'; \
		echo 'RewriteRule . /index.php [L]'; \
		echo ''; \
		echo '# END WordPress'; \
	} > /app/wordpress/.htaccess;

RUN wget -O /var/preview/index.html https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/install/index.html
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/apache2/httpd.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www#g" /app/httpd.conf
RUN apk add --no-cache zip

WORKDIR /var/www
#PHP display error enable or disable
COPY php_ini/php.ini /etc/php8/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php8/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php8/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php8-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php8/php.ini \
;fi

COPY docker-entrypoint.sh /docker-entrypoint.sh

ARG INSTALL_ADDITIONAL_EXTENSIONS
RUN if [ -z "$INSTALL_ADDITIONAL_EXTENSIONS" ] ; then \
echo "No additional PHP extensions added" \
;else \
apk add --no-cache ${INSTALL_ADDITIONAL_EXTENSIONS} \
;fi
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
COPY wp-config.php /app/wordpress/wp-config.php
RUN sed -i "s#{DB_NAME}#${DB_NAME}#g" /app/wordpress/wp-config.php
RUN sed -i "s#{DB_USER}#${DB_USER}#g" /app/wordpress/wp-config.php
RUN sed -i "s#{DB_PASSWORD}#${DB_PASSWORD}#g" /app/wordpress/wp-config.php
RUN sed -i "s#{DB_HOST}#${DB_HOST}#g" /app/wordpress/wp-config.php


# Permission denied inside docker container
ARG USER_ID
ARG GROUP_ID
RUN if [ ${USER_ID} -gt 0 ]; then \
		apk --no-cache add shadow && \
    	if getent group ${GROUP_ID} ; then usermod -u ${USER_ID} -g ${GROUP_ID} nobody; else usermod -u ${USER_ID} nobody; groupmod -g ${GROUP_ID} nobody ; fi \
	;fi
RUN sed -i "s#{USER_ID}#${USER_ID}#g" /docker-entrypoint.sh
RUN sed -i "s#{GROUP_ID}#${GROUP_ID}#g" /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh
CMD /docker-entrypoint.sh & /sbin/runit-wrapper